<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: auth.proto

namespace NaturallyGrpc\Auth;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>NaturallyGrpc.Auth.LoginRequest</code>
 */
class LoginRequest extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>string FLPNo = 1;</code>
     */
    protected $FLPNo = '';
    /**
     * Generated from protobuf field <code>string password = 2;</code>
     */
    protected $password = '';
    /**
     * Generated from protobuf field <code>string dccode = 3;</code>
     */
    protected $dccode = '';

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $FLPNo
     *     @type string $password
     *     @type string $dccode
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Auth::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>string FLPNo = 1;</code>
     * @return string
     */
    public function getFLPNo()
    {
        return $this->FLPNo;
    }

    /**
     * Generated from protobuf field <code>string FLPNo = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setFLPNo($var)
    {
        GPBUtil::checkString($var, True);
        $this->FLPNo = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string password = 2;</code>
     * @return string
     */
    public function getPassword()
    {
        return $this->password;
    }

    /**
     * Generated from protobuf field <code>string password = 2;</code>
     * @param string $var
     * @return $this
     */
    public function setPassword($var)
    {
        GPBUtil::checkString($var, True);
        $this->password = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string dccode = 3;</code>
     * @return string
     */
    public function getDccode()
    {
        return $this->dccode;
    }

    /**
     * Generated from protobuf field <code>string dccode = 3;</code>
     * @param string $var
     * @return $this
     */
    public function setDccode($var)
    {
        GPBUtil::checkString($var, True);
        $this->dccode = $var;

        return $this;
    }

}

