<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: helloworld.proto

namespace GPBMetadata;

class Helloworld
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        $pool->internalAddGeneratedFile(hex2bin(
            "0aa7030a1068656c6c6f776f726c642e70726f746f120a68656c6c6f776f" .
            "726c6422290a0c48656c6c6f52657175657374120c0a046e616d65180120" .
            "012809120b0a03616765180a20012809222a0a0d48656c6c6f5265717565" .
            "737432120c0a046e616d65180120012809120b0a03616765180a20012809" .
            "221d0a0a48656c6c6f5265706c79120f0a076d6573736167651801200128" .
            "0932d0010a0747726565746572123e0a0853617948656c6c6f12182e6865" .
            "6c6c6f776f726c642e48656c6c6f526571756573741a162e68656c6c6f77" .
            "6f726c642e48656c6c6f5265706c79220012400a0953617948656c6c6f32" .
            "12192e68656c6c6f776f726c642e48656c6c6f52657175657374321a162e" .
            "68656c6c6f776f726c642e48656c6c6f5265706c79220012430a0d536179" .
            "48656c6c6f416761696e12182e68656c6c6f776f726c642e48656c6c6f52" .
            "6571756573741a162e68656c6c6f776f726c642e48656c6c6f5265706c79" .
            "220042360a1b696f2e677270632e6578616d706c65732e68656c6c6f776f" .
            "726c64420f48656c6c6f576f726c6450726f746f5001a20203484c576206" .
            "70726f746f33"
        ));

        static::$is_initialized = true;
    }
}

