<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: helloworld.proto

namespace Phuvo\CustomGrpc\Helloworld;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>phuvo.customGrpc.helloworld.AddOrderRequest</code>
 */
class AddOrderRequest extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>.phuvo.customGrpc.helloworld.AddOrderInfo addOrderInfo = 1;</code>
     */
    protected $addOrderInfo = null;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type \Phuvo\CustomGrpc\Helloworld\AddOrderInfo $addOrderInfo
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Helloworld::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>.phuvo.customGrpc.helloworld.AddOrderInfo addOrderInfo = 1;</code>
     * @return \Phuvo\CustomGrpc\Helloworld\AddOrderInfo
     */
    public function getAddOrderInfo()
    {
        return $this->addOrderInfo;
    }

    /**
     * Generated from protobuf field <code>.phuvo.customGrpc.helloworld.AddOrderInfo addOrderInfo = 1;</code>
     * @param \Phuvo\CustomGrpc\Helloworld\AddOrderInfo $var
     * @return $this
     */
    public function setAddOrderInfo($var)
    {
        GPBUtil::checkMessage($var, \Phuvo\CustomGrpc\Helloworld\AddOrderInfo::class);
        $this->addOrderInfo = $var;

        return $this;
    }

}

