<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: helloworld.proto

namespace Phuvo\CustomGrpc\Helloworld;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>phuvo.customGrpc.helloworld.OrderDetail</code>
 */
class OrderDetail extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>int32 id = 1;</code>
     */
    protected $id = 0;
    /**
     * Generated from protobuf field <code>.phuvo.customGrpc.helloworld.Product product = 2;</code>
     */
    protected $product = null;
    /**
     * Generated from protobuf field <code>int32 quantity = 3;</code>
     */
    protected $quantity = 0;
    /**
     * Generated from protobuf field <code>int32 total_price = 4;</code>
     */
    protected $total_price = 0;
    /**
     * Generated from protobuf field <code>int32 order_id = 5;</code>
     */
    protected $order_id = 0;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type int $id
     *     @type \Phuvo\CustomGrpc\Helloworld\Product $product
     *     @type int $quantity
     *     @type int $total_price
     *     @type int $order_id
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Helloworld::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>int32 id = 1;</code>
     * @return int
     */
    public function getId()
    {
        return $this->id;
    }

    /**
     * Generated from protobuf field <code>int32 id = 1;</code>
     * @param int $var
     * @return $this
     */
    public function setId($var)
    {
        GPBUtil::checkInt32($var);
        $this->id = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.phuvo.customGrpc.helloworld.Product product = 2;</code>
     * @return \Phuvo\CustomGrpc\Helloworld\Product
     */
    public function getProduct()
    {
        return $this->product;
    }

    /**
     * Generated from protobuf field <code>.phuvo.customGrpc.helloworld.Product product = 2;</code>
     * @param \Phuvo\CustomGrpc\Helloworld\Product $var
     * @return $this
     */
    public function setProduct($var)
    {
        GPBUtil::checkMessage($var, \Phuvo\CustomGrpc\Helloworld\Product::class);
        $this->product = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int32 quantity = 3;</code>
     * @return int
     */
    public function getQuantity()
    {
        return $this->quantity;
    }

    /**
     * Generated from protobuf field <code>int32 quantity = 3;</code>
     * @param int $var
     * @return $this
     */
    public function setQuantity($var)
    {
        GPBUtil::checkInt32($var);
        $this->quantity = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int32 total_price = 4;</code>
     * @return int
     */
    public function getTotalPrice()
    {
        return $this->total_price;
    }

    /**
     * Generated from protobuf field <code>int32 total_price = 4;</code>
     * @param int $var
     * @return $this
     */
    public function setTotalPrice($var)
    {
        GPBUtil::checkInt32($var);
        $this->total_price = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int32 order_id = 5;</code>
     * @return int
     */
    public function getOrderId()
    {
        return $this->order_id;
    }

    /**
     * Generated from protobuf field <code>int32 order_id = 5;</code>
     * @param int $var
     * @return $this
     */
    public function setOrderId($var)
    {
        GPBUtil::checkInt32($var);
        $this->order_id = $var;

        return $this;
    }

}

