<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: helloworld.proto

namespace Phuvo\CustomGrpc\Helloworld;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>phuvo.customGrpc.helloworld.Order</code>
 */
class Order extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>int32 id = 1;</code>
     */
    protected $id = 0;
    /**
     * Generated from protobuf field <code>string note = 2;</code>
     */
    protected $note = '';
    /**
     * Generated from protobuf field <code>int32 status = 3;</code>
     */
    protected $status = 0;
    /**
     * Generated from protobuf field <code>string address = 4;</code>
     */
    protected $address = '';
    /**
     * Generated from protobuf field <code>string phone = 5;</code>
     */
    protected $phone = '';
    /**
     * Generated from protobuf field <code>.phuvo.customGrpc.helloworld.User user = 6;</code>
     */
    protected $user = null;
    /**
     * Generated from protobuf field <code>int32 total_price = 7;</code>
     */
    protected $total_price = 0;
    /**
     * Generated from protobuf field <code>repeated .phuvo.customGrpc.helloworld.OrderDetail orderDetail = 8;</code>
     */
    private $orderDetail;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type int $id
     *     @type string $note
     *     @type int $status
     *     @type string $address
     *     @type string $phone
     *     @type \Phuvo\CustomGrpc\Helloworld\User $user
     *     @type int $total_price
     *     @type \Phuvo\CustomGrpc\Helloworld\OrderDetail[]|\Google\Protobuf\Internal\RepeatedField $orderDetail
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Helloworld::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>int32 id = 1;</code>
     * @return int
     */
    public function getId()
    {
        return $this->id;
    }

    /**
     * Generated from protobuf field <code>int32 id = 1;</code>
     * @param int $var
     * @return $this
     */
    public function setId($var)
    {
        GPBUtil::checkInt32($var);
        $this->id = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string note = 2;</code>
     * @return string
     */
    public function getNote()
    {
        return $this->note;
    }

    /**
     * Generated from protobuf field <code>string note = 2;</code>
     * @param string $var
     * @return $this
     */
    public function setNote($var)
    {
        GPBUtil::checkString($var, True);
        $this->note = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int32 status = 3;</code>
     * @return int
     */
    public function getStatus()
    {
        return $this->status;
    }

    /**
     * Generated from protobuf field <code>int32 status = 3;</code>
     * @param int $var
     * @return $this
     */
    public function setStatus($var)
    {
        GPBUtil::checkInt32($var);
        $this->status = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string address = 4;</code>
     * @return string
     */
    public function getAddress()
    {
        return $this->address;
    }

    /**
     * Generated from protobuf field <code>string address = 4;</code>
     * @param string $var
     * @return $this
     */
    public function setAddress($var)
    {
        GPBUtil::checkString($var, True);
        $this->address = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string phone = 5;</code>
     * @return string
     */
    public function getPhone()
    {
        return $this->phone;
    }

    /**
     * Generated from protobuf field <code>string phone = 5;</code>
     * @param string $var
     * @return $this
     */
    public function setPhone($var)
    {
        GPBUtil::checkString($var, True);
        $this->phone = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.phuvo.customGrpc.helloworld.User user = 6;</code>
     * @return \Phuvo\CustomGrpc\Helloworld\User
     */
    public function getUser()
    {
        return $this->user;
    }

    /**
     * Generated from protobuf field <code>.phuvo.customGrpc.helloworld.User user = 6;</code>
     * @param \Phuvo\CustomGrpc\Helloworld\User $var
     * @return $this
     */
    public function setUser($var)
    {
        GPBUtil::checkMessage($var, \Phuvo\CustomGrpc\Helloworld\User::class);
        $this->user = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int32 total_price = 7;</code>
     * @return int
     */
    public function getTotalPrice()
    {
        return $this->total_price;
    }

    /**
     * Generated from protobuf field <code>int32 total_price = 7;</code>
     * @param int $var
     * @return $this
     */
    public function setTotalPrice($var)
    {
        GPBUtil::checkInt32($var);
        $this->total_price = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>repeated .phuvo.customGrpc.helloworld.OrderDetail orderDetail = 8;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getOrderDetail()
    {
        return $this->orderDetail;
    }

    /**
     * Generated from protobuf field <code>repeated .phuvo.customGrpc.helloworld.OrderDetail orderDetail = 8;</code>
     * @param \Phuvo\CustomGrpc\Helloworld\OrderDetail[]|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setOrderDetail($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \Phuvo\CustomGrpc\Helloworld\OrderDetail::class);
        $this->orderDetail = $arr;

        return $this;
    }

}

