<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: users.proto

namespace GPBMetadata;

class Users
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        $pool->internalAddGeneratedFile(hex2bin(
            "0ab0020a0b75736572732e70726f746f12134e61747572616c6c79477270" .
            "632e557365727322140a12476574557365724c6973745265717565737422" .
            "430a13476574557365724c697374526573706f6e7365120c0a04636f6465" .
            "180120012809120f0a076d657373616765180220012809120d0a05757365" .
            "727318032001280932710a0b557365725365727669636512620a0b476574" .
            "557365724c69737412272e4e61747572616c6c79477270632e5573657273" .
            "2e476574557365724c697374526571756573741a282e4e61747572616c6c" .
            "79477270632e55736572732e476574557365724c697374526573706f6e73" .
            "65220042360a1b696f2e677270632e6578616d706c65732e68656c6c6f77" .
            "6f726c64420f48656c6c6f576f726c6450726f746f5001a20203484c5762" .
            "0670726f746f33"
        ), true);

        static::$is_initialized = true;
    }
}

